name: yaml-test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run python
      run: python -c "import yaml; print(yaml.__file__)"
    - name: Check yamllint
      run: which yamllint